seed: 42

# Environment configuration
env:
  _target_: mLN.environment.DynamicSpectrumEnv
  num_bs: 3
  num_users: 10
  num_bands: 5
  max_steps: 100
  max_latency: 50.0
  max_power: 23.0  # dBm
  num_power_levels: 4
  power_levels: null  
  fading_coherence: 0.9
  max_interference: 25.0  # mW
  min_sinr: -5.0  # dB
  render_mode: null

# MAML configuration
maml:
  num_meta_tasks: 4
  num_meta_iterations: 1000
  meta_lr: 0.001
  inner_lr: 0.002
  inner_steps: 3
  hidden_dim: 64
  num_blocks: 2
  rollout_len: 100
  eval_interval: 10
  num_eval_tasks: 5
  use_wandb: true
  wandb_project: "maml-spectrum-allocation"
  wandb_name: null

# PPO configuration
ppo:
  total_steps: 200000
  rollout_len: 200
  ppo_epochs: 4
  lr_actor: 3e-4
  lr_critic: 1e-3
  gamma: 0.99
  clip_ratio: 0.2
  value_coeff: 0.5
  entropy_coeff: 0.01
  eval_interval: 10000
  eval_episodes: 5
  use_wandb: true
  wandb_project: "ppo-spectrum-meta"
  wandb_name: null

# Recurrent MAML-PPO configuration
recurrent:
  num_meta_tasks: 4
  num_meta_iterations: 1000
  meta_lr: 0.001
  inner_lr: 0.002
  inner_steps: 3
  clip_ratio: 0.1
  hidden_dim: 64
  lstm_hidden_dim: 32
  num_blocks: 2
  rollout_len: 100
  eval_interval: 10
  num_eval_tasks: 5
  use_wandb: true
  wandb_project: "recurrent-maml-spectrum"
  wandb_name: null


trainer:
  target: train_ppo.PPOTrainer
  env: ${env}
  ppo: ${ppo}
  seed: ${seed}
  device: null

# Hydra configuration
# hydra:
#   run:
#     dir: outputs/{now:%H-%M-%S}
#   sweep:
#     dir: multirun/{now:%H-%M-%S}
#     subdir: ${hydra.job.num}
#   job:
#     config:
#       override_dirname:
#         exclude_keys:
#           - seed
#           - use_wandb


hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    config:
      override_dirname:
        exclude_keys:
          - seed
          - use_wandb
